apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  selector:
    app: combined
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 8080
      targetPort: 3001
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined
  template:
    metadata:
      labels:
        app: combined
    spec:
      containers:
      - name: frontend
        image: seanberlin/frontend:1.0.0
        ports:
        - containerPort: 3000
      - name: backend
        image: seanberlin/backend:1.0.0
        ports:
        - containerPort: 3001
      - name: database
        image: seanberlin/database:1.0.0
        ports:
        - containerPort: 3306
