services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_ENDPOINT=http://backend:8080

  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    environment:
      - NODE_APP_FRONTEND_ENDPOINT=http://frontend:3000

  database:
    build:
      context: ./Database
    ports:
      - "3306:3306"
