version: '3.8'

services:
  frontend:
    build: ./Frontend
    image: seanberlin/frontend:1.0.0
    ports:
      - "3000:3000"

  backend:
    build: ./Backend
    image: seanberlin/backend:1.0.0
    ports:
      - "3001:3000"
    depends_on:
      - database

  database:
    build: ./Database
    image: seanberlin/database:1.0.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
